remote_theme: "mattvh/jekyllthemes"

plugins:
  - jekyll-remote-theme 
  - jekyll-include-cache # add this line to the plugins list if you already have one
  - jekyll-paginate

title: Mi nuevo tema de Jekyll (Colores Oscuros)

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
    # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

collections:
  members:
    output: true
    
    # número de posts por página
paginate: 2
paginate_path: /blog/page:num/

name: Sebastian Acosta
